### ISSUE TITLE
Possible timing attack vulnerability

### ISSUE THREAD

**Issue by Philipp91** [archer884/rwt#4]
Just a quick heads-up from a passer-by:
https://github.com/archer884/rwt/blob/master/src/lib.rs#L58
This comparison might be vulnerable to timing attacks because it's not constant-time. Not sure if that's relevant here at all. I'm reporting such issues to a couple of repositories, please just ignore/close if it isn't applicable here.

**Comment by archer884** [comment]
Because the comparison only goes as far as the first mismatch?

**Comment by Philipp91** [comment]
Yes.

`MacResult` has a nice implementation of the `==` operator that takes care of that:
https://github.com/DaGenix/rust-crypto/blob/master/src/mac.rs#L85
